name: Blueprint request
description: uggest a new infrastructure blueprint
title: "[BLUEPRINT] "
labels: ["blueprint", "enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > **IMPORTANT:** Before submitting, please remove all sensitive data, secrets, tokens, or confidential information. Ensure you've redacted any NDA-covered information, IP addresses, resource names, or security-related details that shouldn't be publicly disclosed.
  - type: textarea
    id: blueprint_purpose
    attributes:
      label: Blueprint Purpose
      description: Describe the purpose of the new blueprint and what scenario it addresses.
    validations:
      required: true
  - type: textarea
    id: target_architecture
    attributes:
      label: Target Architecture
      description: Describe the target architecture for this blueprint.
    validations:
      required: true
  - type: dropdown
    id: implementation_type
    attributes:
      label: Implementation Type
      description: What implementation technology should be used for this blueprint?
      options:
        - "Terraform"
        - "Bicep"
        - "Both Terraform and Bicep"
    validations:
      required: true
  - type: textarea
    id: components
    attributes:
      label: Components
      description: Which existing components should be included in this blueprint?
  - type: textarea
    id: new_components
    attributes:
      label: New Components Needed
      description: Are there any new components that need to be created for this blueprint?
  - type: textarea
    id: azure_services
    attributes:
      label: Azure Services
      description: Which Azure services should this blueprint deploy?
  - type: textarea
    id: similar_blueprints
    attributes:
      label: Similar Blueprints
      description: Are there any similar existing blueprints? How would this differ?
  - type: textarea
    id: target_users
    attributes:
      label: Target Users
      description: Who would use this blueprint and for what purpose?
  - type: textarea
    id: deployment_considerations
    attributes:
      label: Deployment Considerations
      description: Any special considerations for deploying this blueprint?
  - type: textarea
    id: testing_strategy
    attributes:
      label: Testing Strategy
      description: How should this blueprint be tested?
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, diagrams, or references about the blueprint request here.
